Traceback (most recent call last):
  File "D:\users\anaconda3\lib\site-packages\jupyter_cache\executors\utils.py", line 64, in single_nb_execution
    **kwargs,
  File "D:\users\anaconda3\lib\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "D:\users\anaconda3\lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "D:\users\anaconda3\lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "D:\users\anaconda3\lib\asyncio\base_events.py", line 579, in run_until_complete
    return future.result()
  File "D:\users\anaconda3\lib\site-packages\nbclient\client.py", line 664, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "D:\users\anaconda3\lib\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "D:\users\anaconda3\lib\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import random

def rand_data():
    global data
    n=int(input())
    data=[]
    for i in range(n):
        data.append( random.randint(0,100000) )

rand_data()
print(data)
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mStdinNotImplementedError[0m                  Traceback (most recent call last)
[1;32m<ipython-input-5-a26d2de9b0de>[0m in [0;36m<module>[1;34m[0m
[0;32m      8[0m         [0mdata[0m[1;33m.[0m[0mappend[0m[1;33m([0m [0mrandom[0m[1;33m.[0m[0mrandint[0m[1;33m([0m[1;36m0[0m[1;33m,[0m[1;36m100000[0m[1;33m)[0m [1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0;32m      9[0m [1;33m[0m[0m
[1;32m---> 10[1;33m [0mrand_data[0m[1;33m([0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m     11[0m [0mprint[0m[1;33m([0m[0mdata[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m

[1;32m<ipython-input-5-a26d2de9b0de>[0m in [0;36mrand_data[1;34m()[0m
[0;32m      3[0m [1;32mdef[0m [0mrand_data[0m[1;33m([0m[1;33m)[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[0;32m      4[0m     [1;32mglobal[0m [0mdata[0m[1;33m[0m[1;33m[0m[0m
[1;32m----> 5[1;33m     [0mn[0m[1;33m=[0m[0mint[0m[1;33m([0m[0minput[0m[1;33m([0m[1;33m)[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m      6[0m     [0mdata[0m[1;33m=[0m[1;33m[[0m[1;33m][0m[1;33m[0m[1;33m[0m[0m
[0;32m      7[0m     [1;32mfor[0m [0mi[0m [1;32min[0m [0mrange[0m[1;33m([0m[0mn[0m[1;33m)[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m

[1;32mD:\users\anaconda3\lib\site-packages\ipykernel\kernelbase.py[0m in [0;36mraw_input[1;34m(self, prompt)[0m
[0;32m    853[0m         [1;32mif[0m [1;32mnot[0m [0mself[0m[1;33m.[0m[0m_allow_stdin[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[0;32m    854[0m             raise StdinNotImplementedError(
[1;32m--> 855[1;33m                 [1;34m"raw_input was called, but this frontend does not support input requests."[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m    856[0m             )
[0;32m    857[0m         return self._input_request(str(prompt),

[1;31mStdinNotImplementedError[0m: raw_input was called, but this frontend does not support input requests.
StdinNotImplementedError: raw_input was called, but this frontend does not support input requests.

